name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: version
      description: Which version does the problem appear on?
      placeholder: v3.0.5
    validations:
      required: true
  - type: dropdown
    id: sql-type
    attributes:
      label: Which kind of SQL does the problem appear on?
      multiple: true
      options:
        - MySQL
        - Flink
        - Spark
        - Hive
        - Postgre
        - Trino
        - Impala
        - Any Others
  - type: textarea
    id: sql-content
    attributes:
      label:  SQL content
      placeholder: SELECT * FROM table
      render: markdown
  - type: textarea
    id: js-code
    attributes:
      label:  JavasScript/TypeScript code
      placeholder: SELECT * FROM table
      render: markdown
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

